services:
  api:
    container_name: fastapi-app
    image: fastapi
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
      - 5432:5432
    volumes:
      - ./:/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true

  postgres:
    image: postgres 
    environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        
    volumes:
         - postgres-db:/var/lib/postgresql

volumes:
    postgres-db:

